import type { CaseFile, CaseSolution } from '@/types/game.types';
import { decodeSolution } from '@/core/engine.logic';

export const CASE_001: CaseFile = {
  id: '001',
  number: '001',
  title: 'لغز الغرفة 407',
  subtitle: 'جريمة الغرفة المغلقة: حين تنطق الأقفال بالحقيقة',
  difficulty: 'متوسط',
  status: 'مفتوحة',
  intro:
    'وُجد رجل الأعمال "طارق منصور" مقتولاً داخل غرفته 407 بفندق السرو عند الساعة 11:30 ليلاً. الغرفة مقفلة بمزلاج معدني وسقاطة داخلية محكمة، والنوافذ مغلقة من الداخل في الطابق الرابع، مما جعل الحادثة تبدو كغرفة مغلقة مستحيلة. مهمتك إعادة ترتيب أحداث تلك الليلة وكشف كيف تم القفل من الخارج ومن المستفيد من صمت الضحية.',
  closedTruth:
    'المزلاج الداخلي لم يُقفل من الداخل؛ لقد قفلته حيلة ميكانيكية دقيقة نُفذت من خارج الباب عبر سحب شريط تثبيت بلاستيكي وسلك رفيع قبل قصه وإخفائه.',
  initialTimelineId: 't3',
  victim: {
    id: 'tariq',
    name: 'طارق منصور',
    role: 'رجل الأعمال (المتوفى داخل الغرفة 407)',
    tag: 'VICTIM // قتيل مسرح الجريمة',
    summary: 'وُجد رجل الأعمال طارق منصور مقتولاً داخل غرفته 407 بفندق السرو عند الساعة 11:30 ليلاً بضربة غادرة على الرأس.',
    knownInformation: 'وُجد مقتولاً داخل الغرفة 407 عند الساعة 11:30 ليلاً بضربة غادرة على الرأس. الغرفة مقفلة بمزلاج معدني داخلي وسقاطة محكمة.',
    detail: 'رجل أعمال معروف في قطاع المقاولات، قدم للفندق لمقابلة شركائه وتسوية خلافات مالية. أظهر فحص الجثة وفاته نتيجة كسر منخسف في الجمجمة بأداة صلبة راضة.',
    statusLabel: 'متوفى // DECEASED',
    portraitUrl: '/assets/characters/tariq.png',
  },
  initialBoardItems: [
    { kind: 'suspect', id: 'tariq', x: 280, y: 130 },
    { kind: 'timeline', id: 't3', x: 580, y: 130 },
  ],
  suspects: [
    {
      id: 'salem',
      name: 'سالم النجار',
      role: 'موظف الاستقبال',
      suspectType: 'موظف الاستقبال',
      age: 29,
      accent: 'SN',
      portrait: 'ملف شخصي / SN',
      knownInformation: 'المسؤول عن تسجيل النزلاء وتسليم المفاتيح ومراقبة حركة البهو.',
      summary: 'سلوكه مرتبك جداً ويتلعثم بالتحقيق، لكن ارتباكه ناتج عن جرم آخر لا القتل.',
      alibi: 'يدعي أنه لم يغادر مكتب الاستقبال طوال الليل إلا لدقائق معدودة لتبديل ورديته.',
      detail: 'استغل انشغال الجميع وسرق مبلغ 500 دينار من صندوق الأمانات في توقيت متزامن (10:40 ليلاً)، ويخشى كشف السرقة وافتضاح أمره.',
      behavioralNotes: 'يتلعثم بالحديث وتتعرق جبينه كلما ذُكر صندوق الأمانات. يتحسس جيب سترته الأيمن بعصبية مفرطة، ويبلع ريقه بصعوبة طالباً كأس ماء كل بضع دقائق.',
      lastSeen: '10:42 ليلاً — خلف مكتب الاستقبال',
      relevantTimelineIds: ['t2', 't5'],
      testimony: [
        {
          statementId: 'salem-stmt-1',
          text: '«كنت وحدي في مكتب الاستقبال طوال نوبة عملي، ولم أرتكب أي مخالفة أو ألمس أي شيء لا يخصني.»',
        },
        {
          statementId: 'salem-stmt-2',
          text: '«أنا مرتبك فقط لأن الشرطة ملأت الفندق ولا أحب التحقيقات، وليس لأنني أخفي أي سر أو جرم في جيبي!»',
        },
      ],
      challenges: [
        {
          statementId: 'salem-stmt-2',
          requiredDeductionId: 'contradiction-salem',
          effectiveness: 'decisive',
          successDialogue:
            'ينهار سالم ويمسح عرقه بيدين ترتعشان ويخرج رزمة النقود: «أرجوك يا حضرة المحقق! أنا لم أقتل أحداً! كل ما فعلته أنني استغللت انشغال الجميع وسرقت 500 دينار من صندوق الأمانات عند 10:40 ليلاً... ورأيت ليلى تنزل مسرعة من الطابق الرابع عند 10:50 وبيدها حقيبتها متوترة جداً! خذ المال كاملاً، أنا مجرد سارق ولست قاتلاً!»',
          failDialogue:
            'يبلع سالم ريقه بصعوبة: «لا أرى علاقة لهذا الاستنتاج بما أقوله... أنا فقط متوتر من وجود الشرطة.»',
          unlockedClue: 'اعتراف سالم بسرقة 500 دينار وتأكيده رؤية ليلى عائدة بارتباك من الطابق الرابع عند 10:50 ليلاً.',
          breaksSuspect: true,
          composureDelta: -100,
        },
      ],
    },
    {
      id: 'mariam',
      name: 'مريم الخالد',
      role: 'مشرفة التدبير المنزلي',
      suspectType: 'طاقم الخدمة',
      age: 36,
      accent: 'MK',
      portrait: 'ملف شخصي / MK',
      knownInformation: 'المسؤولة عن التدبير المنزلي وعاملات النظافة في الطابق الرابع.',
      summary: 'تدعي ضياع البطاقة الرئيسية، لكنها استعملتها لأخذ هدية ثمينة وتخشى تهمة السرقة.',
      alibi: 'تدعي أنها فقدت بطاقتها الماستر في فترة الظهيرة ولم تصعد للطابق الرابع ليلاً.',
      detail: 'استخدمت البطاقة قبل الحادث بساعة (09:45 ليلاً) لأخذ ساعة يد ثمينة تركها الضحية ولم تبلغ الإدارة خشية اتهامها بالسرقة.',
      behavioralNotes: 'تخفض رأسها نحو الأرض وتتشابك أصابع يديها بقوة. صوتها خافت مرتعش يكاد لا يُسمع، وتظهر عليها علامات الندم والخوف الشديد من خسارة وظيفتها.',
      lastSeen: '09:50 ليلاً — غرفة التدبير المنزلي',
      relevantTimelineIds: ['t1', 't6'],
      testimony: [
        {
          statementId: 'mariam-stmt-1',
          text: '«فقدت بطاقتي الماستر ظهر اليوم ولم أستعملها للدخول إلى أي غرفة في الفندق ليلاً.»',
        },
        {
          statementId: 'mariam-stmt-2',
          text: '«لم أقترب من الغرفة 407 وقت وقوع الجريمة، ولا أعلم كيف فُتح الباب أو من دخل الغرفة.»',
        },
      ],
      challenges: [
        {
          statementId: 'mariam-stmt-1',
          requiredDeductionId: 'contradiction-mariam',
          effectiveness: 'decisive',
          successDialogue:
            'تجهش مريم بالبكاء وتخرج علبة صغيرة: «أرجوك لا تسجنّي يا سيدي! لم أقتل طارق ولم أرَه قط... دخلت عند 09:45 ليلاً لأخذ ساعة يد تركها على المنضدة كهدية لمشرفة النظافة، ومكثت دقيقتين فقط وغادرت قبل العاشرة! لم تكن هناك أي جريمة حينها!»',
          failDialogue:
            'تخفض مريم رأسها بخوف: «أنا عاملة بسيطة ولا أفهم ما ترمي إليه بهذا الاستنتاج.»',
          unlockedClue: 'ثبوت براءة مريم من القتل واقتصار تواجدها على دقيقتين عند 09:45 ليلاً لأخذ الساعة.',
          breaksSuspect: true,
          composureDelta: -100,
        },
      ],
    },
    {
      id: 'nabil',
      name: 'نبيل الراعي',
      role: 'نزيل الغرفة المجاورة 406',
      suspectType: 'نزيل مجاور',
      age: 42,
      accent: 'NR',
      portrait: 'ملف شخصي / NR',
      knownInformation: 'رجل أعمال ومنافس تجاري يقيم في الغرفة 406 الملاصقة مباشرة لغرفة الضحية.',
      summary: 'يدعي أنه كان نائماً ولم يسمع شيئاً، رغم ضبط تسجيلات تجسس حديثة بهاتفه.',
      alibi: 'يؤكد أنه خلد للنوم باكراً عند العاشرة مساءً ولم يستيقظ إلا على جلبة قدوم الشرطة.',
      detail: 'عُثر في هاتفه على تسجيلات صوتية حديثة عبر الجدار المشترك تشير لمحاولته التجسس الصناعي على صفقات الضحية وسجل مشادة القتل.',
      behavioralNotes: 'يتصنع النعاس واللامبالاة ببرود، لكن حركات عينيه تتابعان هاتف المحقق وقلم التدوين بحذر شديد. تبدو على ملامحه علامات السهر واليقظة التامة عكس ادعاء النوم المبكر.',
      lastSeen: '10:30 ليلاً — ممر الطابق الرابع',
      relevantTimelineIds: ['t1', 't3'],
      testimony: [
        {
          statementId: 'nabil-stmt-1',
          text: '«خلدت للنوم مبكراً عند العاشرة مساءً في غرفتي 406، وكنت في نوم عميق ولم أسمع أي حركة أو جلبة في الممر أو الغرفة المجاورة.»',
        },
        {
          statementId: 'nabil-stmt-2',
          text: '«علاقتي بطارق كانت علاقة تنافس تجاري شريفة ولا مصلحة لي في التلصص عليه أو معرفة ما يدور في غرفته.»',
        },
      ],
      challenges: [
        {
          statementId: 'nabil-stmt-1',
          requiredDeductionId: 'contradiction-nabil',
          effectiveness: 'decisive',
          successDialogue:
            'يتبدد برود نبيل المصطنع ويشيح بوجهه خجلاً وتوتراً: «تسجيلات هاتفي؟! حسناً، أعترف... وضعت لاقطاً صوتياً على الجدار المشترك للتجسس على صفقاته المالية. سمعت الشجار بوضوح عند 10:42 ليلاً، وسمعت صوت ليلى تصرخ وصوت سقوط طارق على الأرض! لكنني لم أتدخل لأنني خشيت افتضاح أمر تجسسي. ليلى هي من كانت في الغرفة معه!»',
          failDialogue:
            'يتثاءب نبيل باصطناع: «كلام فارغ... كنت نائماً طوال المساء وهذا الاستنتاج لا يثبت عكس ذلك.»',
          unlockedClue: 'تسجيل صوتي من هاتف نبيل يثبت وقوع الشجار والضربة القاتلة عند 10:42 ليلاً وسماع صوت ليلى بمسرح الجريمة.',
          breaksSuspect: true,
          composureDelta: -100,
        },
      ],
    },
    {
      id: 'layla',
      name: 'ليلى عمران',
      role: 'الشريكة والمديرة المالية',
      suspectType: 'شريكة تجارية',
      age: 34,
      accent: 'LO',
      portrait: 'ملف شخصي / LO',
      knownInformation: 'شريكة الضحية ومديرة حساباته، تواجدت بالفندق لمراجعة تسويات مالية سنوية.',
      summary: 'تدعي وجودها في مقهى البهو طوال المساء لمراجعة الأوراق المحاسبية مع الضحية دون الصعود لغرفته.',
      alibi: 'تقول إنها جلست في مقهى البهو تراجع الأوراق ولم تصعد إلى الطابق الرابع بعد العشاء.',
      detail: 'كشف طارق مؤخراً اختلاسات مالية بملايين الدنانير من الحسابات المشتركة ووجه لها إنذاراً حاسماً بتقديم بلاغ للنائب العام صباح اليوم التالي.',
      behavioralNotes: 'تفرك يديها بتوتر متواصل وتتجنب النظر المباشر في عيني المحقق عند ذكر الساعة 10:45 ليلاً. نبرة صوتها حادة ومصطنعة، وتكرر جملة "كنت بالأسفل طوال الوقت" بحرص مريب ولا ترمش إلا نادراً.',
      lastSeen: '10:45 ليلاً — ممر الطابق الرابع قرب 407',
      relevantTimelineIds: ['t1', 't2', 't3', 't4', 't5'],
      testimony: [
        {
          statementId: 'layla-stmt-1',
          text: '«وصلت إلى فندق السرو قبيل التاسعة مساءً لتسوية الأوراق المحاسبية السنوية مع طارق في بهو الفندق كما نفعل كل عام.»',
        },
        {
          statementId: 'layla-stmt-2',
          text: '«لم أغادر مقهى البهو إطلاقاً بين العاشرة والحادية عشرة والنصف ليلاً، وكان موظف الاستقبال شاهداً على وجودي المستمر هناك.»',
        },
        {
          statementId: 'layla-stmt-3',
          text: '«بالتأكيد لم أصعد إلى الغرفة 407؛ فالجميع يعلم أن الغرفة كانت مقفلة بمزلاجها الحديدي الداخلي، ويستحيل على أي شخص إغلاق هذا المزلاج إلا إذا كان بداخل الغرفة لحظة الجريمة!»',
        },
        {
          statementId: 'layla-stmt-4',
          text: '«طارق كان صديقاً وشريكاً عزيزاً، ولا أملك أي دافع أو مصلحة مالية في إنهاء حياته أو إسكاته.»',
        },
        {
          statementId: 'layla-stmt-5',
          text: '«حسناً، صعدت للطابق الرابع بضع دقائق فقط لرؤية طارق، لكنني وجدته ميتاً بالفعل والباب موصد بالمزلاج فرجعت أدراجي مذعورة!»',
          initial: false,
        },
      ],
      challenges: [
        {
          statementId: 'layla-stmt-2',
          requiredDeductionId: 'contradiction-layla',
          effectiveness: 'strong',
          successDialogue:
            'يبهت وجه ليلى وتشيح بنظرها بارتباك شديد: «سجل البطاقة الإلكترونية عند 10:45 ليلاً؟! لابد... لابد أن شخصاً آخر استخدم بطاقتي... حسناً، صعدت لبضع دقائق فقط، لكنني أقسم أنني لم أقتل طارق!»',
          failDialogue:
            'تهز ليلى رأسها ببرود: «هذه الحجة لا تدحض حقيقة أنني بقيت في الأسفل. وفر جهدك لشبهة حقيقية.»',
          unlockedClue: 'سقوط عذر ليلى بالبقاء في البهو وثبوت تواجدها في ممر الطابق الرابع عند 10:45 ليلاً.',
          unlocksStatementIds: ['layla-stmt-5'],
          breaksSuspect: false,
          composureDelta: -50,
        },
        {
          statementId: 'layla-stmt-3',
          requiredDeductionId: 'contradiction-latch',
          effectiveness: 'decisive',
          successDialogue:
            'تتسمر نظرات ليلى على حقيقة خدش السلك المجهري وبقايا شريط التثبيت البلاستيكي، وتتراجع إلى الخلف بأنفاس لاهثة منهارة بالبكاء: «حسناً... حسناً! أوقف هذا فوراً! صعدت إليه للتفاوض حول الاختلاسات، وعندما هددني بإحالتي للنائب العام غاب عقلي وضربته بالتحفة المعدنية... ثم ثبتت شريط التثبيت وسحبت السلك من خارج الباب لإسقاط المزلاج وقصصت الطرف بالمقص! نعم... أنا من أقفل الغرفة من الخارج!»',
          failDialogue:
            'ترسم ليلى ابتسامة باردة متكلفة: «تكهنات فارغة لا تدحض الحقيقة الفيزيائية للمزلاج الداخلي المغلق بالسقاطة. هات ما يثبت إمكانية إقفاله من الخارج أولاً!»',
          unlockedClue: 'اعتراف ليلى الصريح بارتكاب الجريمة واستخدام حيلة شريط التثبيت والسلك لإسقاط المزلاج الداخلي من الخارج.',
          breaksSuspect: true,
          composureDelta: -100,
        },
        {
          statementId: 'layla-stmt-5',
          requiredDeductionId: 'contradiction-latch',
          effectiveness: 'decisive',
          successDialogue:
            'تنهار دفاعات ليلى وتسقط دموعها على الطاولة: «توقّف عن محاصرتي... الفحص المجهري فضح كل شيء! لم أجد الغرفة مقفلة... أنا من أقفل المزلاج بالسلك وشريط التثبيت بعد أن قتلته!»',
          failDialogue:
            'تصرخ ليلى بعصبية: «أخبرتك أنني وجدته ميتاً! هذا الاستنتاج لا ينفي أقوالي.»',
          unlockedClue: 'اعتراف ليلى الصريح بارتكاب الجريمة واستخدام حيلة شريط التثبيت والسلك لإسقاط المزلاج الداخلي من الخارج.',
          breaksSuspect: true,
          composureDelta: -100,
        },
      ],
      interrogationTruths: [
        {
          statementId: 'layla-stmt-3',
          requiredEvidenceId: 'latch',
          successDialogue:
            'تتسمر نظرات ليلى على صورة الخدش المجهري، وتتراجع إلى الخلف بأنفاس مضطربة: "حسناً... حسناً! أوقف هذا فوراً! صعدت إليه للتفاوض، وعندما هددني بالنائب العام فقدت أعصابي... ثبتت شريط التثبيت وسحبت السلك من فتحة الباب الخارجية بعد إغلاقه! لكنني لم أكن أريد قتله!"',
          failDialogue:
            'ترسم ليلى ابتسامة باردة متكلفة وتشبك أصابعها: "أهذا كل ما تملكه في جعبتك أيها المحقق؟ مجرد تكهنات فارغة لا تدحض حقيقة أن الباب وُجد مقفلاً من الداخل. عد عندما تملك دليلاً حقيقياً."',
          unlockedClue: 'اعتراف صريح من ليلى بإسقاط المزلاج الداخلي من الخارج باستخدام حيلة السلك وشريط التثبيت.',
        },
      ],
    },
  ],
  locations: [
    {
      id: 'room-407',
      name: 'الغرفة 407',
      type: 'مسرح الجريمة المغلق',
      summary: 'مزلاج معدني مقفل، جثة الضحية، ونوافذ محكمة الإغلاق.',
      detail: 'وُجد رجل الأعمال طارق منصور مقتولاً بضربة على الرأس. المزلاج الداخلي مغلق تماماً، مع خدش احتكاك أبيض غير مألوف على الحافة العلوية لإطار الباب الخشبي.',
      clue: 'خدش احتكاك أبيض على أعلى إطار الباب',
      imageLabel: 'مخطط الغرفة 407',
      environmentalDetails: [
        'المزلاج الداخلي والسقاطة مقفولان بإحكام',
        'النوافذ محكمة الإغلاق من الداخل في الطابق الرابع',
        'فنجان قهوة وأوراق تسوية مالية ممزقة على المكتب',
      ],
      evidenceIds: ['latch', 'card-log', 'victim-phone'],
    },
    {
      id: 'service-corridor',
      name: 'ممر الطابق الرابع',
      type: 'ممر النزلاء والخدمة',
      summary: 'ممر هادئ وسلة مهملات بجوار مخرج الطوارئ.',
      detail: 'ممر مفروش بالسجاد يصل بين الغرف ومصعد النزلاء ومخرج الطوارئ. عثر في سلة المهملات على قطعة بلاستيكية مشبوهة.',
      clue: 'سلة المهملات قرب باب الطوارئ',
      imageLabel: 'مخطط ممر الطابق الرابع',
      environmentalDetails: [
        'كاميرا الممر تغطي المصعد فقط ولا ترصد باب الغرفة 407 مباشرة',
        'سلة مهملات صغيرة تحوي نفايات حديثة',
        'باب الغرفة 406 ملاصق للغرفة 407 بجدار مشترك',
      ],
      evidenceIds: ['zip-tie', 'bug-record'],
    },
    {
      id: 'lobby-reception',
      name: 'الاستقبال والبهو',
      type: 'منطقة عامة',
      summary: 'مكتب الاستقبال، صندوق الأمانات، ومقهى البهو.',
      detail: 'المكان الذي ادعت ليلى وجودها فيه طوال المساء، وقربه يقع مكتب الاستقبال حيث ارتكب سالم سرقته.',
      clue: 'صندوق أمانات الفندق خلف كاونتر الاستقبال',
      imageLabel: 'مخطط بهو الفندق',
      environmentalDetails: [
        'سجل النزلاء وكاميرا مراقبة تغطي المدخل الرئيسي',
        'صندوق الأمانات به عجز قدره 500 دينار',
        'طاولات مقهى البهو حيث تركت ليلى حقيبتها الشخصية',
      ],
      evidenceIds: ['layla-bag', 'safe-shortage'],
    },
  ],
  evidence: [
    {
      id: 'latch',
      label: 'مزلاج الباب الداخلي',
      type: 'آلية إغلاق ميكانيكية',
      foundAt: 'الغرفة 407',
      locationId: 'room-407',
      summary: 'مزلاج معدني مثبت بأعلى إطار الباب، وُجد مغلقاً بالسقاطة من الداخل.',
      detail: 'مزلاج معدني تقليدي مثبت بأعلى باب الغرفة 407. الفحص المبدئي بالعين المجردة لا يظهر كسراً مباشراً، ولكن السقاطة والشق العلوي لإطار الباب يتطلبان فحصاً مجهرياً عالي التكبير للتحقق من أي تلاعب ميكانيكي خارجي.',
      discoveredText: 'أظهر الفحص البصري للمنظار الجنائي وجود آثار ميكانيكية دقيقة عند الحافة العلوية وسن القفل.',
      clues: [
        'المزلاج يحتاج إلى فحص مجهري لكشف آثار الاحتكاك الدقيقة',
      ],
      relatedSuspectIds: ['layla'],
      relatedTimelineIds: ['t3', 't4'],
      importance: 'محوري',
      imageUrl: '/images/evidence/door-latch-macro.jpg',
      hotspots: [
        {
          id: 'latch-scratch',
          title: 'خدش احتكاك مجهري',
          x: 59.0,
          y: 36.5,
          radius: 6.5,
          clue: 'خدش احتكاك طولي أبيض على السقاطة وإطار الباب يثبت أن المزلاج أُسقط بسحب سلك رفيع مشدود عبر الفتحة العلوية من خارج الغرفة.',
          category: 'mechanical',
        },
        {
          id: 'nylon-residue',
          title: 'بقايا بوليمر بلاستيكي',
          x: 54.5,
          y: 50.0,
          radius: 5.0,
          clue: 'بقايا نايلون بوليمر دقيقة عالقة في سن القفل تطابق ميكروسكوبياً نوع البلاستيك لشريط التثبيت (Zip-tie) المقطوع.',
          category: 'forensic',
        },
      ],
    },
    {
      id: 'zip-tie',
      label: 'شريط تثبيت بلاستيكي مقطوع (Zip-tie)',
      type: 'أداة ميكانيكية',
      foundAt: 'ممر الطابق الرابع',
      locationId: 'service-corridor',
      summary: 'قطعة بلاستيكية مقطوعة بعناية عثر عليها في سلة الممر.',
      detail: 'عُثر على قطره الصغير في سلة مهملات الممر، وتتطابق آثاره ومقاساته مع الحز الموجود بإطار الباب وسطح المزلاج الداخلي.',
      discoveredText: 'استُخدم الشريط كحلقة وصل مع سلك رفيع لسحب المزلاج وإسقاطه في مجراه، قبل قطع الطرف البارز بالمقص وسحبه للخارج.',
      clues: [
        'قُطع الشريط بأداة معدنية حادة صغيرة',
        'تطابق نوع البلاستيك مع الآثار العالقة في مزلاج الغرفة 407',
      ],
      relatedSuspectIds: ['layla'],
      relatedTimelineIds: ['t4'],
      importance: 'محوري',
      imageUrl: '/images/evidence/zip-tie-macro.jpg',
    },
    {
      id: 'layla-bag',
      label: 'قاطع أسلاك بحقيبة ليلى (Wire cutter)',
      type: 'أداة جريمة مادية',
      foundAt: 'الاستقبال والبهو',
      locationId: 'lobby-reception',
      summary: 'قاطع أسلاك معدني صغير عُثر عليه داخل حقيبة ليلى الشخصية.',
      detail: 'قاطع أسلاك معدني صغير (Wire cutter) وُجد في الجيب الداخلي لحقيبة يد ليلى الجلدية. يتطلب فحص الشفرة تكبيراً دقيقاً للتحقق من أي شوائب دهان أو بوليمر عالقة.',
      discoveredText: 'الفحص المجهري لقاطع الأسلاك كشف عن شفرات حادة تحمل آثاراً مطابقة للمواد المعثور عليها في مسرح الجريمة.',
      clues: [
        'قاطع أسلاك بحجم دقيق يتطابق مع قطع شريط التثبيت البلاستيكي',
      ],
      relatedSuspectIds: ['layla'],
      relatedTimelineIds: ['t4', 't5'],
      importance: 'محوري',
      imageUrl: '/images/evidence/wire-cutter-macro.jpg',
      hotspots: [
        {
          id: 'cutter-paint-fleck',
          title: 'آثار دهان وبوليمر على الشفرة',
          x: 70.0,
          y: 41.5,
          radius: 6.5,
          clue: 'فحص فكي القاطع المعدني يظهر بقايا مجهرية من دهان إطار الباب الأبيض وشظايا نايلون مطابقة لشريط التثبيت، مما يربط القاطع مباشرة بحيلة الغرفة المغلقة.',
          category: 'forensic',
        },
      ],
    },
    {
      id: 'card-log',
      label: 'سجل بطاقات الدخول الرقمية',
      type: 'سجل رقمي مشفر',
      foundAt: 'الغرفة 407',
      locationId: 'room-407',
      summary: 'يُظهر مغادرة ليلى للغرفة 407 الساعة 10:45 ليلاً.',
      detail: 'يُظهر سجل القفل الإلكتروني خروج بطاقة ليلى عمران من الغرفة 407 الساعة 10:45 ليلاً، قبل إقفال المزلاج عبر سحب السلك من الخارج بحركة سريعة.',
      discoveredText: 'سجل البطاقة يدحض ادعاء ليلى ببقائها في البهو، ويثبت أنها كانت داخل الغرفة وغادرتها قبل اكتشاف الجثة.',
      clues: [
        'ليلى تواجدت داخل الغرفة حتى 10:45 ليلاً',
        'لم يُفتح الباب بأي بطاقة أخرى بعد مغادرتها',
      ],
      relatedSuspectIds: ['layla'],
      relatedTimelineIds: ['t2', 't4'],
      importance: 'محوري',
    },
    {
      id: 'victim-phone',
      label: 'رسائل التهديد بهاتف طارق',
      type: 'مستند رقمي',
      foundAt: 'الغرفة 407',
      locationId: 'room-407',
      summary: 'إنذار حاسم من طارق لليلى بتقديم بلاغ الاختلاسات صباح الغد.',
      detail: 'رسالة نصية موجهة لليلى عند 09:30: "كشفت جميع تلاعباتك المصرفية، إما إعادة الأموال الليلة أو أن أوراق الإحالة للنيابة ستكون على مكتب النائب العام صباح الغد".',
      discoveredText: 'الرسالة توضح الدافع القوي لليلى للتخلص من شريكها قبل حلول الصباح لحماية نفسها من السجن.',
      clues: [
        'دافع الانتقام ومنع تقديم البلاغ للنائب العام',
        'تحديد موعد للتفاوض داخل الغرفة 407',
      ],
      relatedSuspectIds: ['layla'],
      relatedTimelineIds: ['t1', 't2'],
      importance: 'مهم',
    },
    {
      id: 'safe-shortage',
      label: 'عجز صندوق الأمانات (500 دينار)',
      type: 'وثيقة مالية',
      foundAt: 'الاستقبال والبهو',
      locationId: 'lobby-reception',
      summary: 'عجز مالي يفسر ارتباك سالم وتلعثمه أثناء التحقيق.',
      detail: 'تقرير الجرد أثبت نقص 500 دينار من صندوق الأمانات سُحبت عند الساعة 10:40 ليلاً، وهو سبب هلع سالم ورعبه من الشرطة.',
      discoveredText: 'ارتباك سالم سببه سرقة الصندوق للتستر على ديونه الشخصية، ولا علاقة له بحادثة القتل في الطابق الرابع.',
      clues: [
        'سالم بريء من دم الضحية لكنه متورط في سرقة مالية',
        'توقيت غيابه عن المكتب كان لإخفاء المبلغ المسروق',
      ],
      relatedSuspectIds: ['salem'],
      relatedTimelineIds: ['t2', 't5'],
      importance: 'مهم',
    },
    {
      id: 'bug-record',
      label: 'تسجيلات التجسس بهاتف نبيل',
      type: 'ملف صوتي تجسسي',
      foundAt: 'ممر الطابق الرابع',
      locationId: 'service-corridor',
      summary: 'تسجيل صوتي لمشادة حادة بين طارق وامرأة عند 10:42 ليلاً.',
      detail: 'التسجيل المضبوط بهاتف نبيل يكشف محاولته التجسس الصناعي، وتُسمع فيه مشادة كلامية بين طارق وامرأة يتبعها صوت ضربة حادة ثم صوت سحب معدني وسقوط.',
      discoveredText: 'التسجيل يثبت أن نبيل كان يتنصت على الصفقات ولم يرتكب الجريمة، لكنه يوثق وجود امرأة في الغرفة وقت القتل.',
      clues: [
        'القاتل امرأة كانت تتشاجر مع الضحية',
        'توقيت وقوع الجريمة الدقيق هو 10:42 ليلاً',
      ],
      relatedSuspectIds: ['nabil', 'layla'],
      relatedTimelineIds: ['t3'],
      importance: 'مهم',
    },
    {
      id: 'master-card',
      label: 'سجل بطاقة الماستر الخاصة بمريم',
      type: 'سجل إلكتروني',
      foundAt: 'الغرفة 407',
      locationId: 'room-407',
      summary: 'سجل يُظهر استخدام بطاقة مريم عند 09:45 ليلاً لدقيقتين فقط.',
      detail: 'أظهرت مراجعة القفل الإلكتروني استخدام بطاقة مريم عند 09:45 ليلاً لمدة دقيقتين فقط، حيث دخلت لأخذ الهدية ثم غادرت قبل وصول ليلى أو وقوع الجريمة.',
      discoveredText: 'مريم لم تكن في الغرفة وقت القتل؛ ادعاء ضياع البطاقة كان مجرد غطاء لتبرير اختفاء الهدية التي أخذتها.',
      clues: [
        'مريم بريئة من القتل',
        'تواجدها كان مبكراً وانتهى قبل العاشرة ليلاً',
      ],
      relatedSuspectIds: ['mariam'],
      relatedTimelineIds: ['t1', 't6'],
      importance: 'عادي',
    },
  ],
  timeline: [
    {
      id: 't1',
      time: '09:30 ليلاً',
      title: 'رسالة التهديد بالإحالة للنيابة',
      location: 'الغرفة 407',
      locationId: 'room-407',
      detail: 'طارق يرسل إنذاراً حاسماً لليلى يطالبها بإعادة الأموال المختلسة الليلة أو مواجهة النائب العام صباح الغد.',
      tone: 'neutral',
      relatedSuspectIds: ['layla'],
      relatedEvidenceIds: ['victim-phone'],
    },
    {
      id: 't2',
      time: '10:20 ليلاً',
      title: 'صعود ليلى وسرقة الصندوق',
      location: 'الاستقبال / الغرفة 407',
      locationId: 'room-407',
      detail: 'ليلى تصعد للطابق الرابع وتدخل الغرفة 407 ببطاقتها للتفاوض، بينما يستغل سالم هدوء البهو لسرقة 500 دينار.',
      tone: 'warning',
      relatedSuspectIds: ['layla', 'salem'],
      relatedEvidenceIds: ['card-log', 'safe-shortage'],
    },
    {
      id: 't3',
      time: '10:42 ليلاً',
      title: 'المشادة والضربة القاتلة',
      location: 'الغرفة 407',
      locationId: 'room-407',
      detail: 'فشل التفاوض؛ نبيل يسجل مشادة حادة بين طارق وليلى تلتها ضربة قاتلة أفقدت الضحية حياته.',
      tone: 'important',
      relatedSuspectIds: ['layla', 'nabil'],
      relatedEvidenceIds: ['bug-record', 'latch'],
    },
    {
      id: 't4',
      time: '10:45 ليلاً',
      title: 'الخروج وتنفيذ حيلة الغرفة المغلقة',
      location: 'ممر الطابق الرابع',
      locationId: 'service-corridor',
      detail: 'ليلى تغادر الغرفة 407، وتغلق المزلاج الداخلي من الخارج بسحب شريط التثبيت البلاستيكي والسلك، ثم تقطعه بقاطع الأسلاك.',
      tone: 'important',
      relatedSuspectIds: ['layla'],
      relatedEvidenceIds: ['card-log', 'latch', 'zip-tie', 'layla-bag'],
    },
    {
      id: 't5',
      time: '10:50 ليلاً',
      title: 'عودة ليلى للبهو واصطناع الحجة',
      location: 'الاستقبال والبهو',
      locationId: 'lobby-reception',
      detail: 'ليلى تعود لمقهى البهو وبحقيبتها قاطع الأسلاك، مدعية أنها لم تغادر البهو إطلاقاً، وتلاحظ ارتباك سالم.',
      tone: 'warning',
      relatedSuspectIds: ['layla', 'salem'],
      relatedEvidenceIds: ['layla-bag', 'safe-shortage'],
    },
    {
      id: 't6',
      time: '11:30 ليلاً',
      title: 'اكتشاف الجثة واقتحام الغرفة',
      location: 'الغرفة 407',
      locationId: 'room-407',
      detail: 'مشرفة النظافة والشرطة تكسران الباب بعد عدم استجابة النزيل، ليجدوا الغرفة مقفلة بمزلاجها الداخلي وجثة طارق على الأرض.',
      tone: 'neutral',
      relatedSuspectIds: ['mariam'],
      relatedEvidenceIds: ['latch', 'master-card'],
    },
  ],
  contradictions: [
    {
      id: 'contradiction-latch',
      title: 'حيلة الغرفة المغلقة وتناقض المزلاج الداخلي',
      description:
        'زعمت ليلى أن الغرفة مقفلة بمزلاج داخلي محكم يستحيل إغلاقه من الخارج، لكن الفحص المجهري كشف خدش السلك وبقايا النايلون البلاستيكية، مثبتاً استخدام حيلة ميكانيكية لإسقاط المزلاج بعد خروجها.',
      suspectId: 'layla',
      relatedEvidenceIds: ['latch', 'zip-tie'],
      relatedTimelineIds: ['t4'],
      requiredHotspotIds: ['latch-scratch'],
      requiredConnections: [
        {
          itemAId: 'latch',
          itemAKind: 'evidence',
          itemBId: 'zip-tie',
          itemBKind: 'evidence',
          description: 'ربط المزلاج الداخلي بشريط التثبيت البلاستيكي المقطوع',
        },
      ],
    },
    {
      id: 'contradiction-layla',
      title: 'ادعاء ليلى بالبقاء في البهو وسجل البطاقات',
      description:
        'تدعي ليلى أنها جلست في البهو طوال المساء ولم تصعد للطابق الرابع، لكن سجل بطاقات الدخول الإلكترونية يثبت دخولها وخروجها من الغرفة 407 عند الساعة 10:45 ليلاً.',
      suspectId: 'layla',
      relatedEvidenceIds: ['card-log', 'layla-bag'],
      relatedTimelineIds: ['t2', 't4'],
      requiredConnections: [
        {
          itemAId: 'layla',
          itemAKind: 'suspect',
          itemBId: 'card-log',
          itemBKind: 'evidence',
          description: 'مواجهة ادعاء ليلى بسجل بطاقات الدخول الإلكترونية',
        },
      ],
    },
    {
      id: 'contradiction-salem',
      title: 'ارتباك سالم وعجز صندوق الأمانات',
      description:
        'سلوك سالم المرتبك وتلعثمه بالتحقيق لا يعودان لجريمة القتل، بل لخوفه من اكتشاف سرقته لمبلغ 500 دينار من صندوق الأمانات في توقيت متزامن.',
      suspectId: 'salem',
      relatedEvidenceIds: ['safe-shortage'],
      relatedTimelineIds: ['t2', 't5'],
      requiredConnections: [
        {
          itemAId: 'salem',
          itemAKind: 'suspect',
          itemBId: 'safe-shortage',
          itemBKind: 'evidence',
          description: 'ربط ارتباك سالم بعجز صندوق الأمانات',
        },
      ],
    },
    {
      id: 'contradiction-nabil',
      title: 'نوم نبيل المزعوم وتسجيلات التجسس',
      description:
        'يدعي نبيل أنه كان نائماً بعمق ولم يسمع شيئاً، في حين أن هاتفه يحوي تسجيلاً صوتياً حياً للشجار والضربة القاتلة مسجلاً عند الساعة 10:42 ليلاً.',
      suspectId: 'nabil',
      relatedEvidenceIds: ['bug-record'],
      relatedTimelineIds: ['t3'],
      requiredConnections: [
        {
          itemAId: 'nabil',
          itemAKind: 'suspect',
          itemBId: 'bug-record',
          itemBKind: 'evidence',
          description: 'ربط نوم نبيل المزعوم بتسجيلات التجسس بهاتفه',
        },
        {
          itemAId: 'bug-record',
          itemAKind: 'evidence',
          itemBId: 't3',
          itemBKind: 'timeline',
          description: 'ربط التسجيل الصوتي بحدث المشادة في خط الزمن عند 10:42 لإثبات التوقيت الدقيق',
        },
      ],
    },
    {
      id: 'contradiction-mariam',
      title: 'ادعاء مريم بضياع البطاقة وسجل الدخول المبكر',
      description:
        'تدعي مريم أنها فقدت بطاقتها الرئيسية نهاراً ولم تستخدمها، لكن مراجعة القفل الإلكتروني أثبتت دخولها للغرفة 407 عند الساعة 09:45 ليلاً لدقيقتين فقط، مما يبرئها من القتل ويثبت مغادرتها قبل وقوع الجريمة.',
      suspectId: 'mariam',
      relatedEvidenceIds: ['master-card'],
      relatedTimelineIds: ['t1', 't6'],
      requiredConnections: [
        {
          itemAId: 'mariam',
          itemAKind: 'suspect',
          itemBId: 'master-card',
          itemBKind: 'evidence',
          description: 'مواجهة ادعاء مريم بسجل استخدام بطاقة الماستر',
        },
      ],
    },
    {
      id: 'contradiction-motive',
      title: '\u062f\u0627\u0641\u0639 \u0627\u0644\u0627\u062e\u062a\u0644\u0627\u0633\u0627\u062a: \u062a\u0647\u062f\u064a\u062f \u0637\u0627\u0631\u0642 \u0644\u064a\u0644\u0649 \u0628\u0627\u0644\u0625\u062d\u0627\u0644\u0629 \u0644\u0644\u0646\u064a\u0627\u0628\u0629 \u0627\u0644\u0639\u0627\u0645\u0629',
      description:
        '\u0623\u0631\u0633\u0644 \u0637\u0627\u0631\u0642 \u0625\u0646\u0630\u0627\u0631\u0627\u064b \u0646\u0647\u0627\u0626\u064a\u0627\u064b \u0644\u064a\u0644\u0649 \u064a\u0637\u0627\u0644\u0628\u0647\u0627 \u0628\u0625\u0639\u0627\u062f\u0629 \u0627\u0644\u0645\u0628\u0627\u0644\u063a \u0627\u0644\u0645\u062e\u062a\u0644\u0633\u0629 \u0627\u0644\u0644\u064a\u0644\u0629 \u0623\u0648 \u062a\u0642\u062f\u064a\u0645 \u0645\u0644\u0641\u0627\u062a \u0627\u0644\u0627\u062e\u062a\u0644\u0627\u0633 \u0644\u0644\u0646\u064a\u0627\u0628\u0629 \u0627\u0644\u0639\u0627\u0645\u0629 \u0635\u0628\u0627\u062d \u0627\u0644\u063a\u062f\u060c \u0645\u0645\u0627 \u064a\u062b\u0628\u062a \u0627\u0644\u062f\u0627\u0641\u0639 \u0627\u0644\u0645\u0628\u0627\u0634\u0631 \u0644\u064a\u0644\u0649 \u0644\u0644\u062a\u062e\u0644\u0635 \u0645\u0646 \u0634\u0631\u064a\u0643\u0647\u0627 \u0642\u0628\u0644 \u062d\u0644\u0648\u0644 \u0627\u0644\u0635\u0628\u0627\u062d.',
      suspectId: 'layla',
      relatedEvidenceIds: ['victim-phone'],
      relatedTimelineIds: ['t1'],
      requiredConnections: [
        {
          itemAId: 'layla',
          itemAKind: 'suspect',
          itemBId: 'victim-phone',
          itemBKind: 'evidence',
          description: '\u0631\u0628\u0637 \u0644\u064a\u0644\u0649 \u0628\u0631\u0633\u0627\u0626\u0644 \u062a\u0647\u062f\u064a\u062f \u0637\u0627\u0631\u0642 \u0627\u0644\u062f\u0627\u0644\u0629 \u0639\u0644\u0649 \u0627\u0644\u062f\u0627\u0641\u0639 \u0627\u0644\u0645\u0627\u0644\u064a',
        },
        {
          itemAId: 'victim-phone',
          itemAKind: 'evidence',
          itemBId: 't1',
          itemBKind: 'timeline',
          description: 'ربط رسائل التهديد بإنذار الإحالة للنيابة صباح الغد في خط الزمن',
        },
      ],
    },
  ],
  // Solution is securely obfuscated via Base64 to prevent inspection cheating
  _encodedSolution:
    'eyJjdWxwcml0SWQiOiJsYXlsYSIsIm1vdGl2ZSI6ItmD2LTZgSDYp9mE2LbYrdmK2Kkg2YTYp9iu2KrZhNin2LPYp9iq2YfYpyDYp9mE2YXYp9mE2YrYqSDZiNiq2YfYr9mK2K/ZhyDYqNiq2YLYr9mK2YXZh9inINmE2YTYudiv2KfZhNipIiwibWV0aG9kIjoi2KXZgtmB2KfZhCDYp9mE2YXYstmE2KfYrCDYp9mE2K/Yp9iu2YTZiiDZhdmGINin2YTYrtin2LHYrCDYqNmI2KfYs9i32Kkg2LTYsdmK2Lcg2KrYq9io2YrYqiDYqNmE2KfYs9iq2YrZg9mKINmI2LPZhNmDINir2YUg2YLYtdmHINmI2LPYrdio2Ycg2KjYudivINil2LrZhNin2YIg2KfZhNio2KfYqCIsInRpbWUiOiIxMDo0MCDigJQgMTA6NTAg2YTZitmE2KfZiyIsImNyaXRpY2FsRXZpZGVuY2VJZHMiOlsibGF0Y2giLCJ6aXAtdGllIiwibGF5bGEtYmFnIiwiY2FyZC1sb2ciXSwiY3JpdGljYWxUaW1lbGluZUV2ZW50SWRzIjpbInQyIiwidDMiLCJ0NCIsInQ1Il0sInJldmVhbFN0ZXBzIjpbeyJpZCI6InJldmVhbC0xIiwidGltZSI6IjEwOjIwINmE2YrZhNin2YsiLCJ0aXRsZSI6Iti12LnZiNivINmE2YrZhNmJINmE2YTYutix2YHYqSDZhNmE2KrZgdin2YjYtiIsImRlc2NyaXB0aW9uIjoi2LXYudiv2Kog2YTZitmE2Ykg2LnZhdix2KfZhiDZhNmE2LrYsdmB2KkgNDA3INio2LnYryDYpdmG2LDYp9ixINi32KfYsdmCINmE2YfYpyDYqNin2YHYqti22KfYrSDYo9mF2LEg2KfYrtiq2YTYp9iz2KfYqtmH2Kcg2YjYpdit2KfZhNiq2YfYpyDZhNmE2YbYp9im2Kgg2KfZhNi52KfZhSDZgdmKINin2YTYtdio2KfYrS4iLCJldmlkZW5jZUlkcyI6WyJ2aWN0aW0tcGhvbmUiLCJjYXJkLWxvZyJdfSx7ImlkIjoicmV2ZWFsLTIiLCJ0aW1lIjoiMTA6NDIg2YTZitmE2KfZiyIsInRpdGxlIjoi2KfZhNin2LTYqtio2KfZgyDZiNin2YTYttix2KjYqSDYp9mE2YLYp9iq2YTYqSIsImRlc2NyaXB0aW9uIjoi2LnZhtiv2YXYpyDYsdmB2LYg2LfYp9ix2YIg2KfZhNiq2LHYp9is2Lkg2YjYo9i12LEg2LnZhNmJINiq2LPZhNmK2YUg2KfZhNmF2YTZgdin2Kog2YTZhNmC2LbYp9ih2Iwg2YbYtNio2Kog2YXYtNin2K/YqSDYp9mG2KrZh9iqINio2LbYsdioINmE2YrZhNmJINmE2Ycg2KjYo9iv2KfYqSDYrdin2K/YqSDYo9mI2K/YqiDYqNit2YrYp9iq2YcuIiwiZXZpZGVuY2VJZHMiOlsiYnVnLXJlY29yZCJdfSx7ImlkIjoicmV2ZWFsLTMiLCJ0aW1lIjoiMTA6NDUg2YTZitmE2KfZiyIsInRpdGxlIjoi2KrZhtmB2YrYsCDYrdmK2YTYqSDYp9mE2LrYsdmB2Kkg2KfZhNmF2LrZhNmC2KkiLCJkZXNjcmlwdGlvbiI6Itir2KjYqtiqINmE2YrZhNmJINi02LHZiti3INin2YTYqtir2KjZitiqINin2YTYqNmE2KfYs9iq2YrZg9mKIChaaXAtdGllKSDYqNin2YTYs9mC2KfYt9ipINmI2LPZhNmDINix2YHZiti5INi52KjYsSDYp9mE2K3Yp9mB2Kkg2KfZhNi52YTZiNmK2Kkg2YTYpdi32KfYsSDYp9mE2KjYp9io2Iwg2KvZhSDYrtix2KzYqiDZiNij2LrZhNmC2Kog2KfZhNio2KfYqCDZiNiz2K3YqNiqINin2YTYs9mE2YMg2KjZgtmI2Kkg2K3YqtmJINin2YbYstmE2YIg2KfZhNmF2LLZhNin2Kwg2YHZiiDZhdis2LHYp9mHINin2YTYr9in2K7ZhNmKLiIsImV2aWRlbmNlSWRzIjpbImxhdGNoIiwiemlwLXRpZSJdfSx7ImlkIjoicmV2ZWFsLTQiLCJ0aW1lIjoiMTA6NDYg2YTZitmE2KfZiyIsInRpdGxlIjoi2YLYtSDYp9mE2LPZhNmDINmI2KXYrtmB2KfYoSDYp9mE2KPYr9in2KkiLCJkZXNjcmlwdGlvbiI6Itin2LPYqtiu2K/ZhdiqINmC2KfYt9i5INin2YTYo9iz2YTYp9mDINin2YTYtdi62YrYsSDZhdmGINit2YLZitio2KrZh9inINmE2YLYtSDYt9ix2YEg2KfZhNi02LHZiti3INin2YTYqNmE2KfYs9iq2YrZg9mKINmI2LPYrdio2YfYjCDZiNiq2K7ZhNi12Kog2YXZhiDYp9mE2LTYsdmK2Lcg2YHZiiDYs9mE2Kkg2KfZhNmF2YXYsSDZiNin2K3YqtmB2LjYqiDYqNin2YTZgtin2LfYuSDZgdmKINit2YLZitio2KrZh9inINmI2LnYp9iv2Kog2YTZhNio2YfZiC4iLCJldmlkZW5jZUlkcyI6WyJsYXlsYS1iYWciLCJ6aXAtdGllIl19XSwiY2hvaWNlcyI6eyJtb3RpdmVzIjpbItmD2LTZgSDYp9mE2LbYrdmK2Kkg2YTYp9iu2KrZhNin2LPYp9iq2YfYpyDYp9mE2YXYp9mE2YrYqSDZiNiq2YfYr9mK2K/ZhyDYqNiq2YLYr9mK2YXZh9inINmE2YTYudiv2KfZhNipIiwi2LPYsdmC2Kkg2YXYqNmE2LogNTAwINiv2YrZhtin2LEg2YXZhiDYtdmG2K/ZiNmCINij2YXYp9mG2KfYqiDYp9mE2YHZhtiv2YIiLCLYp9mE2KrYrNiz2LMg2KfZhNi12YbYp9i52Yog2YjYs9ix2YLYqSDYo9iz2LHYp9ixINin2YTYtdmB2YLYp9iqINin2YTYqtis2KfYsdmK2KkiXSwibWV0aG9kcyI6WyLYpdmC2YHYp9mEINin2YTZhdiy2YTYp9isINin2YTYr9in2K7ZhNmKINmF2YYg2KfZhNiu2KfYsdisINio2YjYp9iz2LfYqSDYtNix2YrYtyDYqtir2KjZitiqINio2YTYp9iz2KrZitmD2Yog2YjYs9mE2YMg2KvZhSDZgti12Ycg2YjYs9it2KjZhyDYqNi52K8g2KXYutmE2KfZgiDYp9mE2KjYp9ioIiwi2KfZhNiq2LPZhNmEINi52KjYsSDYp9mE2YbYp9mB2LDYqSDYp9mE2K7Yp9ix2KzZitipINmE2YTYt9in2KjZgiDYp9mE2LHYp9io2Lkg2YjYp9mE2K/YrtmI2YQg2KjYp9mE2YXZgdiq2KfYrSDYp9mE2YXYp9iz2KrYsSIsItin2LPYqtiv2LHYp9isINin2YTYttit2YrYqSDZhNmF2LrYp9iv2LHYqSDYp9mE2LrYsdmB2Kkg2KvZhSDZgtiq2YTZhyDZiNil2LnYp9iv2KrZhyDZhNmE2K/Yp9iu2YQiXSwidGltZXMiOlsiMDk6MzAg4oCUIDEwOjAwINmE2YrZhNin2YsiLCIxMDo0MCDigJQgMTA6NTAg2YTZitmE2KfZiyIsIjExOjIwIOKAlCAxMTozNSDZhNmK2YTYp9mLIl19fQ==',
  get solution(): CaseSolution {
    return decodeSolution(this._encodedSolution!);
  },

  // Phase 1D: Evidence-Based Indictment — Case 001 proof requirements
  // Each claim requires a specific validated deduction to file a complete indictment.
  // Presence ≠ Motive: they are separate deductions the player must independently earn.
  accusationConfig: {
    culpritId: 'layla',
    requirements: [
      {
        claimType: 'identity' as const,
        label: '\u0627\u0644\u062d\u0636\u0648\u0631 \u0641\u064a \u0645\u0633\u0631\u062d \u0627\u0644\u062c\u0631\u064a\u0645\u0629',
        requiredDeductionIds: ['contradiction-layla'],
        description: '\u0627\u0633\u062a\u0646\u062a\u0627\u062c \u064a\u062b\u0628\u062a \u062a\u0648\u0627\u062c\u062f \u0627\u0644\u0645\u062a\u0647\u0645 \u062f\u0627\u062e\u0644 \u0627\u0644\u063a\u0631\u0641\u0629 407 \u0648\u0648\u0642\u062a \u0627\u0644\u062c\u0631\u064a\u0645\u0629',
      },
      {
        claimType: 'motive' as const,
        label: '\u0627\u0644\u062f\u0627\u0641\u0639 \u0627\u0644\u0645\u0628\u0627\u0634\u0631 \u0644\u0644\u062c\u0631\u064a\u0645\u0629',
        requiredDeductionIds: ['contradiction-motive'],
        description: '\u0627\u0633\u062a\u0646\u062a\u0627\u062c \u064a\u062b\u0628\u062a \u0648\u062c\u0648\u062f \u062f\u0627\u0641\u0639 \u0648\u0627\u0636\u062d \u0648\u0645\u0628\u0627\u0634\u0631 \u062f\u0641\u0639 \u0627\u0644\u0645\u062a\u0647\u0645 \u0644\u0627\u0631\u062a\u0643\u0627\u0628 \u0627\u0644\u062c\u0631\u064a\u0645\u0629',
      },
      {
        claimType: 'method' as const,
        label: '\u0622\u0644\u064a\u0629 \u062a\u0646\u0641\u064a\u0630 \u0627\u0644\u062c\u0631\u064a\u0645\u0629',
        requiredDeductionIds: ['contradiction-latch'],
        description: '\u0627\u0633\u062a\u0646\u062a\u0627\u062c \u062c\u0646\u0627\u0626\u064a \u064a\u062b\u0628\u062a \u0627\u0644\u0643\u064a\u0641\u064a\u0629 \u0648\u0627\u0644\u0622\u0644\u064a\u0629 \u0627\u0644\u062a\u064a \u0646\u064f\u0641\u0630\u062a \u0628\u0647\u0627 \u0627\u0644\u062c\u0631\u064a\u0645\u0629 \u062f\u0627\u062e\u0644 \u0645\u0633\u0631\u062d \u0627\u0644\u062d\u0627\u062f\u062b',
      },
      {
        claimType: 'opportunity' as const,
        label: '\u0627\u0644\u062a\u0648\u0642\u064a\u062a \u0648\u0627\u0644\u0641\u0631\u0635\u0629',
        requiredDeductionIds: ['contradiction-nabil'],
        description: '\u0627\u0633\u062a\u0646\u062a\u0627\u062c \u0645\u0633\u062a\u0642\u0644 \u064a\u062b\u0628\u062a \u0648\u062c\u0648\u062f \u0627\u0644\u0645\u062a\u0647\u0645 \u0641\u064a \u0627\u0644\u063a\u0631\u0641\u0629 \u0644\u062d\u0638\u0629 \u0627\u0644\u0642\u062a\u0644 \u0648\u064a\u0624\u0643\u062f \u0627\u0644\u062a\u0648\u0642\u064a\u062a \u0628\u062f\u0644\u064a\u0644 \u0645\u0633\u062a\u0642\u0644',
      },
    ],
  },
};
